Settings:
  Enable_Print_Console: false
Groups:
  Skulkers: default
  Beds: default
  Potions: default
  Enchanted_Books: default
  Minecarts: default
  Boats: default
  Banners: default
  Music_Disc: default
  Buckets: default
Items: