name: StackOptimized
version: '1.2'
main: Roman.stackOptimized.StackOptimized
api-version: '1.21'
commands:
  setMaxStackSize:
    description: Set max stack size for item in hand
  stackgui:
    description: Open admin GUI for StackOptimized
  name:
    description: Get name of item in hand
  resetstacks:
    description: Reset all item stack sizes to default values
    permission: stackoptimized.admin